# tomcat
server:
  port: 8081
#spring
spring:
  application:
    name: nacos-consumer
  profiles:
    # 环境配置
    active: dev
  cloud:
    nacos:
      discovery:
        #服务注册地址
        server-addr: 127.0.0.1:8848
      config:
        # 配置中心地址
        server-addr: 127.0.0.1:8848
        # 配置文件格式
        file-extension: yml
        # 共享配置
        shared-dataids: application.yml